//! Concrete tool implementations (WP-1.2 C2): the six-tool minimal face.
//!
//! `read` / `write` / `edit` / `bash` / `grep` / `glob`, each a 1:1 port of
//! the TS reference in `packages/coding-agent/src/tools/*` (edit modes in
//! `src/edit/`). Per-tool deferred surface is listed in each module's doc
//! comment; output text is pinned byte-for-byte by the golden corpus under
//! `tests/goldens/` (generated by `scripts/gen-tool-goldens.ts` against the
//! real TS tools via bun).

pub mod bash;
mod block_context;
pub mod edit;
pub mod glob;
pub mod grep;
mod path_tree;
mod paths;
pub mod read;
mod selector;
pub mod write;

pub use bash::BashTool;
pub use edit::EditTool;
pub use glob::GlobTool;
pub use grep::GrepTool;
pub use read::ReadTool;
pub use write::WriteTool;
